feat: Create RaceTypeLevel
UCLA-Creative-Labs/password pull request #11
Opened 2020-10-27 00:16 UTC by DonLe27

Still need to style it but I need to get some designs from Maggie first

2020-10-27 03:28 UTC, BryanPan342 requested changes
Can we make the `_redirects` page into the `netlify.toml` file.. OR add a `scripts/postbuild.js` to create the `_redirects` file

2020-10-27 03:54 UTC, DonLe27 commented
> Can we make the `_redirects` page into the `netlify.toml` file.. OR add a `scripts/postbuild.js` to create the `_redirects` file

Yup, added to .toml file

2020-10-27 14:52 UTC, BryanPan342 submitted a review, later dismissed
@DonLe27 dude this is freaking dope i love it ❤️

Had some comments on the code after reading it! Just a couple of nits here and there

2020-10-27 14:52 UTC, BryanPan342 commented on src/components/TypeRacerLevel.tsx
> +// Identical to level1 except function name and export.
```suggestion
```

2020-10-27 14:52 UTC, BryanPan342 commented on src/components/App.tsx
> +          Sign In{' '}
what does this do?

2020-10-27 14:52 UTC, BryanPan342 commented on src/components/TypeRacerLevel.tsx
> +        <p style={{ textAlign: 'center' }}>Type Racing</p>
i see this `style={{ textAlign: 'center' }}` a lot.. thoughts about making this a css class?

@UCLA-Creative-Labs/tech would like other ppl's opinion on this too

2020-10-27 14:52 UTC, BryanPan342 commented on src/components/TypeRacerLevel.tsx
> +}
```suggestion
function TextPrompt(props: PromptProps): JSX.Element {
  return (
    <div>
      <form>
        <textarea
          value={props.prompt}
          onChange={(e) => props.setPrompt(e.target.value)}
          className="textPrompt"
        />
      </form>
    </div>
  );
}
```
for consistency

2020-10-27 14:52 UTC, BryanPan342 commented on src/components/TypeRacerLevel.tsx
> +const RaceTrack = React.memo(({ setRestart, setTimeOut }: RaceTrackProps) => {
```suggestion
const RaceTrack = React.memo((props: RaceTrackProps) => {
```
for consistency

2020-10-27 14:52 UTC, BryanPan342 commented on src/components/TypeRacerLevel.tsx
> +                    >
nit: one line this?

2020-10-27 14:52 UTC, BryanPan342 commented on src/components/TypeRacerLevel.tsx
> +  const p = prompts[Math.floor(Math.random() * prompts.length)]; // Triggered weird comma dangle error
maybe make this a function? i see u use it later on line 105

2020-10-27 17:28 UTC, arjunr00 submitted a review, later dismissed
Can you merge `main` into this branch? Then if you can move this new level component into `src/components/Levels/` and make sure `RaceTypeLevel` has all of its components wrapped using `<Level>` with appropriate props that'd be gr8. (See DESIGN_GUIDELINES.md for more info)

(Also, for the merge conflict with `App`, just go with whatever was in `main` already)

2020-10-31 23:05 UTC, BryanPan342 submitted a review, later dismissed
LGTM

2020-10-31 23:22 UTC, BryanPan342 commented
@mergifyio

2020-10-31 23:25 UTC, BryanPan342 commented
@Mergifyio refresh

2020-10-31 23:45 UTC, BryanPan342 approved these changes
BIG THUMBS UP

2020-10-31 23:47 UTC, merged